### ISSUE TITLE
Oversampling does not work for Bragg2DPtycho model

### ISSUE THREAD

**Issue by jangid19** [cdtools-developers/cdtools#11]
# Bug description 

I am trying to simulate the probe on 2x larger real-space array using `oversampling` flag for `Bragg2DPtycho` model. But the shape of the probe and object generated are not the same if `oversampling` is enabled. 

# Expected Behavior

Simulate the probe on larger real-space array using `oversampling`.

# Current Behavior

The shape of probe and object tensors are different, causing `cdtools.tools.interactions.ptycho_2D_sinc` function to throw a  `RuntimeError`.

## Steps to Reproduce

1. Setup `Bragg2DPtycho` model with oversampling = 2

```
model = cdtools.models.Bragg2DPtycho.from_dataset(
    dataset,
    oversampling=2,
    translation_scale=2.5,
    n_modes=1, 
    propagation_distance=200e-6,
)
```

4. Run reconstruction using Adam or LBGFS.

## OS and Package info

* Operating System: Manjaro Linux x86_64
* Python version: 3.12
* Pytorch version: 2.5.1
* NVCC version: 12.6
* cdtools-0.2.0

## Failure Logs

```
Traceback (most recent call last):
  File "/Recon_Sample_LBFGS.py", line 58, in <module>
    for loss in model.LBFGS_optimize(5, dataset, lr=0.1):
  File "/cdtools/src/cdtools/models/base.py", line 492, in AD_optimize
    raise res
  File "/cdtools/src/cdtools/models/base.py", line 457, in target
    result_queue.put(run_epoch(stop_event))
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/models/base.py", line 417, in run_epoch
    loss += optimizer.step(closure).detach().cpu().numpy()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/lib/python3.12/site-packages/torch/optim/optimizer.py", line 487, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/cdtools/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/cdtools/lib/python3.12/site-packages/torch/optim/lbfgs.py", line 330, in step
    orig_loss = closure()
                ^^^^^^^^^
  File "/miniconda3/envs/cdtools/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/models/base.py", line 395, in closure
    sim_patterns = self.forward(*inp)
                   ^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/models/base.py", line 94, in forward
    return self.measurement(self.forward_propagator(self.interaction(*args)))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/models/bragg_2d_ptycho.py", line 453, in interaction
    exit_waves = self.probe_norm * tools.interactions.ptycho_2D_sinc(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/tools/interactions/interactions.py", line 442, in ptycho_2D_sinc
    selections = t.stack([obj[..., tr[0]:tr[0]+probe.shape[-2],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [900, 698] at entry 0 and [900, 696] at entry 1
```

**Comment by allevitan** [comment]
I created a branch with a fix for this and submitted a pull request (#12). If you pull down the bragg_oversampling branch, you can test if it's working now or not :)

**Comment by jangid19** [comment]
Thanks for fixing the oversampling issue. However I suspect that in Bragg geometry, there is still something that is clipping the probe to a specific square window (see attached image of a ZP probe being clipped even after oversampling). To replicate this, set `propagation_distance=1e-3` for a ZP style probe.

On another note, padding does not work anymore (see attached Traceback).
```python
Traceback (most recent call last):
  File "/Recon_Sample_Adam.py", line 33, in <module>
    model = cdtools.models.Bragg2DPtycho.from_dataset(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cdtools/src/cdtools/models/bragg_2d_ptycho.py", line 377, in from_dataset
    obj_view_crop = min(probe.shape[-2], probe.shape[-1]) // 2 + pfc
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
```  
I was able to temporarily fix this by updating the line to `obj_view_crop = min(probe.shape[-2], probe.shape[-1]) // 2 + pfc[-2]`. 

![probe_real_space](https://github.com/user-attachments/assets/10a8a1f9-370d-4bac-b37d-347b29cda423)

**Comment by allevitan** [comment]
Good catch with the padding, I'll look into the issue.

Re: the other issue, I would need to know more about the specific dataset to troubleshoot much further. However, I do have a suspicion regarding what is happening. At the moment, the probe initialization routine first initializes the probe (including any propagation from focus), and then surrounds the initial probe guess with zeros, if needed, based on the oversampling argument. This means that the first guess of the probe can look like this (if this is the probe's initial guess with oversampling=3?) with the initial guess limited to a square window at the center. What happens once you start doing the reconstruction?

I think it would obviously be better if the code did it the other way around: to first pad the initial probe guess, and then do the propagation from focus, which would prevent this kind of effect. Feel free to poke around and suggest a change if you see a good way to update it, otherwise I will try to get to this soon.

**Comment by allevitan** [comment]
I've update the pull request with a slightly more robust fix for the obj_view_crop issue

**Comment by jangid19** [comment]
I am trying to test out the limits of CDTools in reflection geometry with various test patterns that we have at the beamline. I have noticed that the reconstructions look great for propagation distances shorter than 500e-6 m. Past this propagation distance, for highly divergent probes like ZPs, the real space probe is clipped by the square window (maybe at initialization as you suggested) and reconstruction becomes noisy or impossible. Running through multiple epochs does not increase the size of the clipping window in real space (does increase it in Fourier space) fast enough for reconstruction to converge.

I think this behavior is not not limited to a specific dataset and is more general. Please find a screenshot were I set the propagation distance to 1000e-6 m and run the reconstruction for 30 epochs of Adam. The probe is always clipped to a 10 um window in real space (you only see the center of the ZP in real space in the screenshot attached). 

![31_epochs_1000mum](https://github.com/user-attachments/assets/aaef1dcd-9582-46b1-85bb-0e2a08286c94)

**Comment by jangid19** [comment]
Did more testing on the oversampling issue. I kept all other parameters the same (see below) and changed just the oversampling value. 

```python
model = cdtools.models.Bragg2DPtycho.from_dataset(
    dataset,
    oversampling=1, # = 1, or 2, 3, 4
    translation_scale=3,
    n_modes=1, 
    propagation_distance=600e-6, # True value for distance is around 2000e-6
    probe_fourier_crop=pad # = 50 pix
)
``` 
Probe in real space after 20 epochs:
Oversampling: 1
![600mum_oversample_1](https://github.com/user-attachments/assets/991662de-4dbc-47ae-a1e0-25c023a4e3e4)


Oversampling: 2
![600mum_oversample_2](https://github.com/user-attachments/assets/1bbaf8b9-1082-499f-b83e-57d955a53d65)


Oversampling: 3
![600mum_oversample_3](https://github.com/user-attachments/assets/7ae37216-2d4f-4564-932d-42b067980812)


Oversampling: 4
![600mum_oversample_4](https://github.com/user-attachments/assets/02f55891-2de2-49f5-9318-a1acae4d151f)

**Comment by allevitan** [comment]
I suspect that at this point, the challenge you're encountering has more to do with the limits of far-field ptychography than a specific issue with CDTools. The point of the oversampling parameter is to make it possible to do reconstructions when the diffraction pattern is not properly Nyquist sampled, based on the ideas in [this paper](https://doi.org/10.1103/PhysRevA.87.053850). However, working with undersampled diffraction patterns will always degrade the results. For example, using oversampling=4 will lead to a very poorly constrained inverse problem.

If you do have data that you want to work on where the probe has been propagated away from focus to the point where it is much larger than the probe field of view (with oversampling=1), I would suggest looking into Fresnel ptychography (a.k.a. near-field ptychography) in conjunction with the Fresnel scaling theorem, e.g. [this paper](https://doi.org/10.1038/srep01927) or [this follow-up](https://doi.org/10.1364/OE.23.012720). Fresnel ptychography is not currently part of CDTools, but it is on the roadmap. Of course, any developments in that direction are welcomed! It is also implemented in many other ptychography toolboxes, such as ptypy and ptychoshelves. 

I will mark this issue as closed for now.
